// Printable HTML reports for Site Audit and AI Visibility. Opens in a new
// tab with a "Print" prompt — the merchant can save as PDF natively from
// the browser. Single-purpose, no SPA — pure server-rendered HTML so it's
// fast and downloadable.

const express = require('express');
const router = express.Router();
const { shopifyAuth } = require('../middleware/shopifyAuth');
const {
  Audit, AuditIssue, AuditPage,
  AIVisibilityRun, AIVisibilityResult, ShopSettings,
  sequelize,
} = require('../models');

function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

const STYLES = `
  body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; color:#202223; max-width:980px; margin:32px auto; padding:0 32px; line-height:1.55; }
  h1 { font-size:28px; margin:0 0 4px; }
  h2 { font-size:20px; margin:32px 0 12px; padding-bottom:6px; border-bottom:1px solid #e1e3e5; }
  h3 { font-size:15px; margin:20px 0 8px; color:#6d7175; text-transform:uppercase; letter-spacing:0.4px; }
  .meta { color:#6d7175; font-size:13px; margin-bottom:24px; }
  .kpi-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin:24px 0; }
  .kpi { background:#f4f5fa; border-radius:8px; padding:14px 16px; }
  .kpi .v { font-size:28px; font-weight:700; }
  .kpi .l { font-size:12px; color:#6d7175; }
  table { width:100%; border-collapse:collapse; font-size:13px; margin:8px 0 24px; }
  th,td { text-align:left; padding:8px 10px; border-bottom:1px solid #e1e3e5; vertical-align:top; }
  th { background:#fafbfb; font-weight:600; color:#6d7175; text-transform:uppercase; font-size:11px; letter-spacing:0.4px; }
  .sev-error { color:#d72c0d; font-weight:600; }
  .sev-warning { color:#f49342; font-weight:600; }
  .sev-notice { color:#8a8a8a; font-weight:600; }
  .pill { display:inline-block; padding:2px 8px; border-radius:10px; font-size:11px; font-weight:600; background:#f4f5fa; }
  .pill.success { background:#e3f5e1; color:#108043; }
  .pill.danger  { background:#fdece9; color:#d72c0d; }
  .footer { margin-top:48px; padding-top:16px; border-top:1px solid #e1e3e5; color:#6d7175; font-size:12px; text-align:center; }
  @media print { body { margin:16px; } .no-print { display:none; } }
`;

function reportShell({ title, subtitle, body }) {
  return `<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<style>${STYLES}</style>
</head><body>
  <div class="no-print" style="text-align:right;margin-bottom:8px;">
    <button onclick="window.print()" style="padding:8px 16px;background:#1a1a1a;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:13px;font-weight:600;">⤓ Save as PDF / Print</button>
  </div>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">${escapeHtml(subtitle)}</div>
  ${body}
  <div class="footer">Generated by Google Console Analytics · ${new Date().toLocaleString()}</div>
</body></html>`;
}

// ── Site Audit print report ────────────────────────────────────────────────
router.get('/audit/:id', shopifyAuth, async (req, res) => {
  const audit = await Audit.findOne({
    where: { id: req.params.id, shop_id: req.shop.id },
  });
  if (!audit) return res.status(404).send('Audit not found');

  const summary = await AuditIssue.findAll({
    where: { audit_id: audit.id },
    attributes: ['type', 'severity', 'category', [sequelize.fn('COUNT', sequelize.col('id')), 'count']],
    group: ['type', 'severity', 'category'],
    raw: true,
  });

  const errCount  = summary.filter(s => s.severity === 'error').reduce((a, c) => a + Number(c.count), 0);
  const warnCount = summary.filter(s => s.severity === 'warning').reduce((a, c) => a + Number(c.count), 0);
  const noticeCount = summary.filter(s => s.severity === 'notice').reduce((a, c) => a + Number(c.count), 0);

  const sortedIssues = summary
    .map(s => ({ ...s, count: Number(s.count) }))
    .sort((a, b) => {
      const sevOrder = { error: 0, warning: 1, notice: 2 };
      if (sevOrder[a.severity] !== sevOrder[b.severity]) return sevOrder[a.severity] - sevOrder[b.severity];
      return b.count - a.count;
    });

  const pages = await AuditPage.findAll({
    where: { audit_id: audit.id },
    order: [['status_code', 'ASC']],
    limit: 200,
  });

  const body = `
    <div class="kpi-grid">
      <div class="kpi"><div class="v">${audit.score || 0}/100</div><div class="l">Site Health Score</div></div>
      <div class="kpi"><div class="v">${audit.pages_crawled || 0}</div><div class="l">Pages Crawled</div></div>
      <div class="kpi"><div class="v sev-error">${errCount}</div><div class="l">Errors</div></div>
      <div class="kpi"><div class="v sev-warning">${warnCount}</div><div class="l">Warnings</div></div>
    </div>

    <h2>Issues by Type</h2>
    <table>
      <thead><tr><th>Severity</th><th>Issue</th><th>Category</th><th style="text-align:right;">Pages affected</th></tr></thead>
      <tbody>
        ${sortedIssues.map(s => `
          <tr>
            <td><span class="sev-${s.severity}">${escapeHtml(s.severity)}</span></td>
            <td>${escapeHtml(s.type.replace(/_/g, ' '))}</td>
            <td>${escapeHtml(s.category)}</td>
            <td style="text-align:right;font-weight:600;">${s.count}</td>
          </tr>`).join('')}
      </tbody>
    </table>

    <h2>Crawled Pages (first ${pages.length})</h2>
    <table>
      <thead><tr><th>URL</th><th>Status</th><th>Title</th><th style="text-align:right;">Words</th><th style="text-align:right;">Load (ms)</th></tr></thead>
      <tbody>
        ${pages.map(p => `
          <tr>
            <td style="word-break:break-all;max-width:380px;">${escapeHtml(p.url)}</td>
            <td>${p.status_code || '—'}</td>
            <td>${escapeHtml((p.title || '').slice(0, 80))}</td>
            <td style="text-align:right;">${p.word_count || 0}</td>
            <td style="text-align:right;">${p.load_time_ms || 0}</td>
          </tr>`).join('')}
      </tbody>
    </table>
  `;

  res.set('Content-Type', 'text/html; charset=utf-8');
  res.send(reportShell({
    title: `Site Audit Report — ${req.shop.shop_name || req.shop.shop_domain}`,
    subtitle: `Run on ${new Date(audit.created_at).toLocaleString()} · ${audit.audit_url}`,
    body,
  }));
});

// ── AI Visibility print report ─────────────────────────────────────────────
router.get('/ai-visibility/:id', shopifyAuth, async (req, res) => {
  const run = await AIVisibilityRun.findOne({
    where: { id: req.params.id, shop_id: req.shop.id },
  });
  if (!run) return res.status(404).send('Run not found');
  const results = await AIVisibilityResult.findAll({
    where: { run_id: run.id },
    order: [['provider', 'ASC'], ['id', 'ASC']],
  });
  const settings = await ShopSettings.findOne({ where: { shop_id: req.shop.id } });
  const brandName = settings?.ai_brand_name || req.shop.shop_name || req.shop.shop_domain;

  // Per-provider stats
  const byProvider = {};
  for (const r of results) {
    const k = r.provider || 'unknown';
    if (!byProvider[k]) byProvider[k] = { provider: k, total: 0, mentions: 0, citations: 0, brandCited: 0, errors: 0 };
    byProvider[k].total++;
    byProvider[k].mentions += r.brand_mention_count || 0;
    byProvider[k].citations += r.citation_count || 0;
    if (r.brand_cited) byProvider[k].brandCited++;
    if (r.error) byProvider[k].errors++;
  }

  // Per-topic stats
  const byTopic = {};
  for (const r of results) {
    const k = r.topic || 'General';
    if (!byTopic[k]) byTopic[k] = { topic: k, total: 0, mentioned: 0 };
    byTopic[k].total++;
    if (r.brand_mentioned) byTopic[k].mentioned++;
  }

  const body = `
    <div class="kpi-grid">
      <div class="kpi"><div class="v">${run.visibility_score || 0}/100</div><div class="l">Visibility Score</div></div>
      <div class="kpi"><div class="v">${run.mentions_total || 0}</div><div class="l">Total Mentions</div></div>
      <div class="kpi"><div class="v">${run.citations_total || 0}</div><div class="l">Total Citations</div></div>
      <div class="kpi"><div class="v">${run.cited_pages_total || 0}</div><div class="l">Cited Pages</div></div>
    </div>

    <h2>Performance by AI Provider</h2>
    <table>
      <thead><tr><th>Provider</th><th>Prompts</th><th>Mentions</th><th>Brand-cited</th><th>Citations</th><th>Errors</th></tr></thead>
      <tbody>
        ${Object.values(byProvider).map(p => `
          <tr>
            <td><strong>${escapeHtml(p.provider)}</strong></td>
            <td>${p.total}</td>
            <td><span class="pill ${p.mentions > 0 ? 'success' : ''}">${p.mentions}</span></td>
            <td>${p.brandCited}</td>
            <td>${p.citations}</td>
            <td>${p.errors > 0 ? `<span class="sev-error">${p.errors}</span>` : '0'}</td>
          </tr>`).join('')}
      </tbody>
    </table>

    <h2>Performance by Topic</h2>
    <table>
      <thead><tr><th>Topic</th><th>Total Prompts</th><th>Mentioned in</th><th style="text-align:right;">Mention rate</th></tr></thead>
      <tbody>
        ${Object.values(byTopic).sort((a, b) => b.mentioned - a.mentioned).map(t => `
          <tr>
            <td>${escapeHtml(t.topic)}</td>
            <td>${t.total}</td>
            <td>${t.mentioned}</td>
            <td style="text-align:right;font-weight:600;">${t.total > 0 ? Math.round((t.mentioned / t.total) * 100) : 0}%</td>
          </tr>`).join('')}
      </tbody>
    </table>

    <h2>All Prompt Results</h2>
    <table>
      <thead><tr><th>Provider</th><th>Topic</th><th>Prompt</th><th>Mentioned</th><th>Brand cited</th></tr></thead>
      <tbody>
        ${results.map(r => `
          <tr>
            <td>${escapeHtml(r.provider)}</td>
            <td>${escapeHtml(r.topic || '—')}</td>
            <td style="max-width:380px;">${escapeHtml((r.prompt || '').slice(0, 160))}</td>
            <td>${r.brand_mentioned ? `<span class="pill success">Yes (${r.brand_mention_count}×)</span>` : `<span class="pill danger">No</span>`}</td>
            <td>${r.brand_cited ? '<span class="pill success">Yes</span>' : '—'}</td>
          </tr>`).join('')}
      </tbody>
    </table>
  `;

  res.set('Content-Type', 'text/html; charset=utf-8');
  res.send(reportShell({
    title: `AI Visibility Report — ${brandName}`,
    subtitle: `Run on ${new Date(run.created_at).toLocaleString()} · score ${run.visibility_score || 0}/100 · ${results.length} prompt × provider results`,
    body,
  }));
});

module.exports = router;
