const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

// FAQ Q&A pairs attached to a product. AI-generated by default but fully
// editable. Powers FAQPage JSON-LD schema in Structured Markup tab.
const ProductFaq = sequelize.define('ProductFaq', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  shop_id: { type: DataTypes.INTEGER, allowNull: false },
  product_id: { type: DataTypes.INTEGER, allowNull: false, comment: 'FK -> products.id' },
  question: { type: DataTypes.STRING(500), allowNull: false },
  answer: { type: DataTypes.TEXT, allowNull: false },
  sort_order: { type: DataTypes.INTEGER, defaultValue: 0 },
  source: { type: DataTypes.ENUM('ai', 'manual'), defaultValue: 'ai' },
  provider: { type: DataTypes.STRING(40), allowNull: true, comment: 'gemini | groq | openrouter (when source=ai)' },
  status: { type: DataTypes.ENUM('draft', 'approved', 'discarded'), defaultValue: 'draft' },
}, {
  tableName: 'product_faqs',
  indexes: [
    { fields: ['shop_id'] },
    { fields: ['product_id', 'sort_order'] },
  ],
});

module.exports = ProductFaq;
